### ISSUE TITLE
Implement package initialization

### ISSUE THREAD

**Issue by DeepBlockDeepak** [DeepBlockDeepak/RoadTripPlanner#3]
### Description
To enhance our project's structure and import system, we propose adding `__init__.py` files to our subdirectories. This change will explicitly turn these directories into Python packages, improving module resolution and maintainability.

### Objectives
1. **Clarify Module Organization**: Establish clear package-based organization.
2. **Simplify Imports**: Enable more straightforward, relative imports.
3. **Enhance Portability**: Reduce reliance on `sys.path` modifications and other workarounds.

### Tasks
- [x] Add `__init__.py` to each subdirectory (e.g., `src`, `chat_gpt_tools`).
- [x] Update import statements across the project to use relative paths where appropriate.
  - For instance, in `src/routes.py`, change `from src.models import User` to `from .models import User`.
- [x] Test thoroughly to ensure no import errors occur.

### Code Snippets
- Add an empty `__init__.py` file:
  ```bash
  touch src/__init__.py
  ````
- Update an Import Statement:
  ```python
  # Before
  from src.models import User

  # After
  from .models import User
  ```

**Comment by DeepBlockDeepak** [comment]
Currently worked on a large refactor 6b6985a, which uses a new application structure. Though it doesn't resolve this this Issue 3, it will be a direct buildup to the fully realized end goal of __init__ializing the project packages.

**Comment by DeepBlockDeepak** [comment]
Finished with. 5e76965.
